CREATE TABLE BULLHORN_ALERTS
(
    ID NUMBER(19) NOT NULL,
    ALERT_TYPE CHAR(8) NOT NULL,
    FROM_USER VARCHAR2(99) NOT NULL,
    TO_USER VARCHAR2(99) NOT NULL,
    EVENT VARCHAR2(32) NOT NULL,
    REF VARCHAR2(255) NOT NULL,
    TITLE VARCHAR2(255),
    SITE_ID VARCHAR2(99),
    URL CLOB NOT NULL,
    EVENT_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT fk_from_user
        FOREIGN KEY (FROM_USER)
        REFERENCES SAKAI_USER(USER_ID),
    CONSTRAINT fk_to_user
        FOREIGN KEY (TO_USER)
        REFERENCES SAKAI_USER(USER_ID),
    CONSTRAINT fk_site_id
        FOREIGN KEY (SITE_ID)
        REFERENCES SAKAI_SITE(SITE_ID),
);

CREATE SEQUENCE bullhorn_alerts_seq;

CREATE OR REPLACE TRIGGER bullhorn_alerts_bir
BEFORE INSERT ON BULLHORN_ALERTS
FOR EACH ROW

BEGIN
      SELECT bullhorn_alerts_seq.NEXTVAL
      INTO   :new.id
      FROM   dual;
END;
/
